### ISSUE TITLE
Migrate the example standalone XML files to use either YAML configuration files or CLI to provision a server

### ISSUE THREAD

**Issue by jamezp** [wildfly-extras/wildfly-grpc-feature-pack#91]
Currently in the examples a `standalone.xml.*` file is copied from the `ssl` directory. We should use either CLI to configure a server or use YAML to overlay the configure. This allows the configuration to be up to date with the version of WildFly we're using instead of a static version set to a specific WildFly release.

**Comment by ronsigal** [comment]
Thanks, James!!
